### ISSUE TITLE
Is there a way to show inner element outside slick slide?

### ISSUE THREAD

**Issue by BaljitKarwal** [subin-george/slick#1]
I am trying to add some custom quotes style to each slick item and as per design it should be half out of the main slick container. Due to overflow hidden css, my pseudo element(absolute positioned) is not visible outside the main slick slider height. Tried to add overflow-y visible but not working. Any suggestions?
Below is the example before and after pseudo elements added to each item:
`
&:before {
              top: -2px;
              position: absolute;
              left: 10px;
              font-style: italic;
              content: '"';
              font-size: 40px;
              line-height: 16px;
              z-index: 2;
            }
            
&:after {
              top: -2px;
              position: absolute;
              right: 10px;
              font-style: italic;
              content: '"';
              font-size: 40px;
              line-height: 16px;
              z-index: 2;
            }
`

**Comment by BaljitKarwal** [comment]
Resolved it by adding extra margin on top of each item.

**Comment by nickmeagher** [comment]
@karwalbubble Adding a margin-top worked for what I was trying to do as well, I was trying to scale the `.slick-slide` and using margin-top allowed it to not get cut off.
